### PR TITLE
Adds replyEmbed and sendEmbed, messageCommands, made it install (postinstall tsc), and fixed various bugs.

### PR DESCRIPTION
**Pull request by aenriii**
Currently still testing some things (just got an unrelated issue that I'm looking into pertaining to Commands.set/Commands.setGuildCommand) but to my understanding this should be mostly done.

### CODE REVIEW

**Comment by E-boi** [comment]
Hey for the main field of `package.json` I left it look to for `index.js` because of how releasing it works. look at/run [this](https://github.com/E-boi/periljs/blob/main/setup_release.sh) to get a idea what i mean

**Comment by aenriii** [comment]
i'll implement a fix for the package.json that allows both git and npm installations, I've also decided that the json.forEach bug is probably not being fixed in this pr as its just a rate-limiting issue as far as I can tell

**Review by aenriii — COMMENTED** [review]
This changes the json that gets moved to dist/ to package.dist.json, which also gets renamed. this allows for both git and npm installations.

**Comment by E-boi** [comment]
uh https://github.com/jdadonut/periljs/blob/main/package.dist.json#L5

**Comment by aenriii** [comment]
it seems i moved the typescript package declaration and forgot everything else, I'll push the fix in like 2 seconds.

**Comment by aenriii** [comment]
that should do it

**Pull request merged**
